/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file ones_like_tiling_key.h
 * \brief ones_like tiling key
 */

#include "ascendc/host_api/tiling/template_argument.h"

#ifndef _ONES_LIKE_TILING_KEY_H_
#define _ONES_LIKE_TILING_KEY_H_

#define ONES_LIKE_TPL_FP16 1
#define ONES_LIKE_TPL_BF16 2
#define ONES_LIKE_TPL_FP32 3
#define ONES_LIKE_TPL_INT32 4
#define ONES_LIKE_TPL_INT8 5
#define ONES_LIKE_TPL_BOOL 6
#define ONES_LIKE_TPL_UINT8 7

#define ELEMENTWISE_TPL_SCH_MODE_0 0
#define ELEMENTWISE_TPL_SCH_MODE_1 1

ASCENDC_TPL_ARGS_DECL(
    OnesLike,
    ASCENDC_TPL_UINT_DECL(schMode, 1, ASCENDC_TPL_UI_LIST, ELEMENTWISE_TPL_SCH_MODE_0, ELEMENTWISE_TPL_SCH_MODE_1),
    ASCENDC_TPL_DTYPE_DECL(
        dType, ONES_LIKE_TPL_FP16, ONES_LIKE_TPL_BF16, ONES_LIKE_TPL_FP32, ONES_LIKE_TPL_INT32, ONES_LIKE_TPL_INT8,
        ONES_LIKE_TPL_BOOL, ONES_LIKE_TPL_UINT8));

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, ELEMENTWISE_TPL_SCH_MODE_0, ELEMENTWISE_TPL_SCH_MODE_1),
        ASCENDC_TPL_DTYPE_SEL(dType, ONES_LIKE_TPL_FP16)),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, ELEMENTWISE_TPL_SCH_MODE_0, ELEMENTWISE_TPL_SCH_MODE_1),
        ASCENDC_TPL_DTYPE_SEL(dType, ONES_LIKE_TPL_BF16)),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, ELEMENTWISE_TPL_SCH_MODE_0, ELEMENTWISE_TPL_SCH_MODE_1),
        ASCENDC_TPL_DTYPE_SEL(dType, ONES_LIKE_TPL_FP32)),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, ELEMENTWISE_TPL_SCH_MODE_0, ELEMENTWISE_TPL_SCH_MODE_1),
        ASCENDC_TPL_DTYPE_SEL(dType, ONES_LIKE_TPL_INT32)),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, ELEMENTWISE_TPL_SCH_MODE_0, ELEMENTWISE_TPL_SCH_MODE_1),
        ASCENDC_TPL_DTYPE_SEL(dType, ONES_LIKE_TPL_INT8)),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, ELEMENTWISE_TPL_SCH_MODE_0, ELEMENTWISE_TPL_SCH_MODE_1),
        ASCENDC_TPL_DTYPE_SEL(dType, ONES_LIKE_TPL_BOOL)),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, ELEMENTWISE_TPL_SCH_MODE_0, ELEMENTWISE_TPL_SCH_MODE_1),
        ASCENDC_TPL_DTYPE_SEL(dType, ONES_LIKE_TPL_UINT8)), );
#endif