/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* !
 * \file quant_batch_matmul_v3_apt_tiling_key.h
 * \brief
 */
#ifndef QBMMV3_ARCH35_TILING_KEY_H
#define QBMMV3_ARCH35_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

namespace QuantBatchMatmulV3Arch35TilingKey {

#if (defined(ORIG_DTYPE_X1) && defined(ORIG_DTYPE_SCALE))
#define SUPPORT_PERBLOCK             \
    (ORIG_DTYPE_SCALE == DT_FLOAT && \
     (ORIG_DTYPE_X1 == DT_HIFLOAT8 || ORIG_DTYPE_X1 == DT_FLOAT8_E4M3FN || ORIG_DTYPE_X1 == DT_FLOAT8_E5M2))
#else
#define SUPPORT_PERBLOCK false
#endif

// Bias Mode
#define TPL_EXCLUDE_FROM_TEMPLATE 0
#define TPL_CUBE_BIAS_BF16_TEMPLATE 1
#define TPL_CUBE_BIAS_FP16_TEMPLATE 2

// Kernel Type
#define TPL_NO_VEC_EPILOGUE_WITH_MMAPI 0
#define TPL_NO_VEC_EPILOGUE_CUSTOM_GMTOAL1_WITH_MMAPI 1
#define TPL_VEC_EPILOGUE_WITH_MMAPI 2
#define TPL_VEC_EPILOGUE_CUSTOM_GMTOAL1_WITH_MMAPI 3
#define TPL_VEC_EPILOGUE_WITH_CUSTOM_MM 4
#define TPL_NO_VEC_EPILOGUE_CUSTOM_GMTOABL1_WITH_MMAPI 5
#define TPL_NO_VEC_EPILOGUE_WITH_BMMAPI 6
#define TPL_NO_VEC_EPILOGUE_WITH_BMMAPI_NO_BATCH_OUT 7
#define TPL_NO_VEC_EPILOGUE_CUSTOM_GMTOBL1_WITH_MMAPI 8

ASCENDC_TPL_ARGS_DECL(
    QuantBatchMatmulV3, ASCENDC_TPL_UINT_DECL(ATRANS, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, 0, 1),
    ASCENDC_TPL_UINT_DECL(BTRANS, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, 0, 1),
    ASCENDC_TPL_UINT_DECL(
        BIASMODE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, TPL_EXCLUDE_FROM_TEMPLATE, TPL_CUBE_BIAS_BF16_TEMPLATE,
        TPL_CUBE_BIAS_FP16_TEMPLATE),
    ASCENDC_TPL_UINT_DECL(
        KERNELTYPE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, TPL_NO_VEC_EPILOGUE_WITH_MMAPI,
        TPL_NO_VEC_EPILOGUE_CUSTOM_GMTOAL1_WITH_MMAPI, TPL_VEC_EPILOGUE_WITH_MMAPI,
        TPL_VEC_EPILOGUE_CUSTOM_GMTOAL1_WITH_MMAPI, TPL_VEC_EPILOGUE_WITH_CUSTOM_MM,
        TPL_NO_VEC_EPILOGUE_CUSTOM_GMTOABL1_WITH_MMAPI, TPL_NO_VEC_EPILOGUE_WITH_BMMAPI,
        TPL_NO_VEC_EPILOGUE_WITH_BMMAPI_NO_BATCH_OUT, TPL_NO_VEC_EPILOGUE_CUSTOM_GMTOBL1_WITH_MMAPI));

ASCENDC_TPL_SEL(
#if ((!defined(__CCE_AICORE__)) || (defined(ORIG_DTYPE_SCALE) && (ORIG_DTYPE_SCALE == DT_FLOAT || ORIG_DTYPE_SCALE == DT_BF16))) 
    ASCENDC_TPL_ARGS_SEL(       // kernel type {2, 3} * ATRANS {0, 1} * BTRANS {0, 1}
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(ATRANS, ASCENDC_TPL_UI_LIST, 0, 1),
        ASCENDC_TPL_UINT_SEL(BTRANS, ASCENDC_TPL_UI_LIST, 0, 1),
        ASCENDC_TPL_UINT_SEL(BIASMODE, ASCENDC_TPL_UI_LIST, TPL_EXCLUDE_FROM_TEMPLATE), // Bias Mode 只有0
        ASCENDC_TPL_UINT_SEL(KERNELTYPE, 
            ASCENDC_TPL_UI_LIST,
            TPL_VEC_EPILOGUE_WITH_MMAPI, 
            TPL_VEC_EPILOGUE_CUSTOM_GMTOAL1_WITH_MMAPI)),
#endif
#if ((!defined(__CCE_AICORE__)) || (SUPPORT_PERBLOCK))
    ASCENDC_TPL_ARGS_SEL(       // kernel type {4} * ATRANS {0, 1} * BTRANS {0, 1}
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(ATRANS, ASCENDC_TPL_UI_LIST, 0, 1),
        ASCENDC_TPL_UINT_SEL(BTRANS, ASCENDC_TPL_UI_LIST, 0, 1),
        ASCENDC_TPL_UINT_SEL(BIASMODE, ASCENDC_TPL_UI_LIST, TPL_EXCLUDE_FROM_TEMPLATE), // Bias Mode 只有0
        ASCENDC_TPL_UINT_SEL(KERNELTYPE, 
            ASCENDC_TPL_UI_LIST, 
            TPL_VEC_EPILOGUE_WITH_CUSTOM_MM)),
#endif
#if (!defined(__CCE_AICORE__) || (defined(__NPU_ARCH__) && (__NPU_ARCH__ == 5102)))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIC_ONLY),
        ASCENDC_TPL_UINT_SEL(ATRANS, ASCENDC_TPL_UI_LIST, 0, 1),
        ASCENDC_TPL_UINT_SEL(BTRANS, ASCENDC_TPL_UI_LIST, 0, 1),
        ASCENDC_TPL_UINT_SEL(BIASMODE, ASCENDC_TPL_UI_LIST, TPL_EXCLUDE_FROM_TEMPLATE), // Bias Mode 只有0
        ASCENDC_TPL_UINT_SEL(KERNELTYPE, 
            ASCENDC_TPL_UI_LIST, 
            TPL_NO_VEC_EPILOGUE_CUSTOM_GMTOABL1_WITH_MMAPI,
            TPL_NO_VEC_EPILOGUE_WITH_BMMAPI,
            TPL_NO_VEC_EPILOGUE_WITH_BMMAPI_NO_BATCH_OUT,
            TPL_NO_VEC_EPILOGUE_CUSTOM_GMTOBL1_WITH_MMAPI)),
#endif
    ASCENDC_TPL_ARGS_SEL(       // kernel type {0, 1} * ATRANS {0, 1} * BTRANS {0, 1}
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIC_ONLY),
        ASCENDC_TPL_UINT_SEL(ATRANS, ASCENDC_TPL_UI_LIST, 0, 1),
        ASCENDC_TPL_UINT_SEL(BTRANS, ASCENDC_TPL_UI_LIST, 0, 1),
        ASCENDC_TPL_UINT_SEL(BIASMODE, ASCENDC_TPL_UI_LIST, TPL_EXCLUDE_FROM_TEMPLATE),
        ASCENDC_TPL_UINT_SEL(KERNELTYPE, 
            ASCENDC_TPL_UI_LIST, 
            TPL_NO_VEC_EPILOGUE_WITH_MMAPI, 
            TPL_NO_VEC_EPILOGUE_CUSTOM_GMTOAL1_WITH_MMAPI))
);
} // namespace QuantBatchMatmulV3_Arch35_TilingKey
#endif