/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License")
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* !
 * \file lp_loss_tiling_key.h
 * \brief lploss tiling key
 */

#ifndef _LP_LOSS_TILING_KEY_H_
#define _LP_LOSS_TILING_KEY_H_
#define REDUCTION_BIT_WIDTH 2
#define LPLOSS_SUM 1
#define LPLOSS_MEAN 2
#define LPLOSS_TPL_FP16 10
#define LPLOSS_TPL_FP32 20
#define LPLOSS_TPL_BFP16 30
#include "atvoss/reduce/reduce_tiling_key_decl.h"

ASCENDC_TPL_ARGS_DECL(LpLoss, REDUCE_TPL_KEY_DECL(),
    ASCENDC_TPL_UINT_DECL(Reduction, REDUCTION_BIT_WIDTH, ASCENDC_TPL_UI_LIST, 0, LPLOSS_SUM, LPLOSS_MEAN),
    ASCENDC_TPL_UINT_DECL(Dtype, BIT_WIDTH, ASCENDC_TPL_UI_LIST, LPLOSS_TPL_FP16, LPLOSS_TPL_FP32, LPLOSS_TPL_BFP16));

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
        ASCENDC_TPL_UINT_SEL(PatternID, ASCENDC_TPL_UI_LIST, 0),
        ASCENDC_TPL_UINT_SEL(LoopARCount, ASCENDC_TPL_UI_LIST, 0),
        ASCENDC_TPL_UINT_SEL(LoopInnerARCount, ASCENDC_TPL_UI_LIST, 0),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, 0),
        ASCENDC_TPL_UINT_SEL(Dtype, ASCENDC_TPL_UI_LIST, LPLOSS_TPL_FP16)),

    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
        ASCENDC_TPL_UINT_SEL(PatternID, ASCENDC_TPL_UI_LIST, 0),
        ASCENDC_TPL_UINT_SEL(LoopARCount, ASCENDC_TPL_UI_LIST, 0),
        ASCENDC_TPL_UINT_SEL(LoopInnerARCount, ASCENDC_TPL_UI_LIST, 0),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, 0),
        ASCENDC_TPL_UINT_SEL(Dtype, ASCENDC_TPL_UI_LIST, LPLOSS_TPL_FP32)),

    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
        ASCENDC_TPL_UINT_SEL(PatternID, ASCENDC_TPL_UI_LIST, 0),
        ASCENDC_TPL_UINT_SEL(LoopARCount, ASCENDC_TPL_UI_LIST, 0),
        ASCENDC_TPL_UINT_SEL(LoopInnerARCount, ASCENDC_TPL_UI_LIST, 0),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, 0),
        ASCENDC_TPL_UINT_SEL(Dtype, ASCENDC_TPL_UI_LIST, LPLOSS_TPL_BFP16)),

    ASCENDC_TPL_ARGS_SEL(
        REDUCE_TPL_KEY_SEL_EMPTY(),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, LPLOSS_SUM, LPLOSS_MEAN),
        ASCENDC_TPL_UINT_SEL(Dtype, ASCENDC_TPL_UI_LIST, LPLOSS_TPL_FP32)),

    ASCENDC_TPL_ARGS_SEL(
        REDUCE_TPL_KEY_SEL_AR_NORMAL(),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, LPLOSS_SUM, LPLOSS_MEAN),
        ASCENDC_TPL_UINT_SEL(Dtype, ASCENDC_TPL_UI_LIST, LPLOSS_TPL_FP32)),

    ASCENDC_TPL_ARGS_SEL(
        REDUCE_TPL_KEY_SEL_AR_GROUP(),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, LPLOSS_SUM, LPLOSS_MEAN),
        ASCENDC_TPL_UINT_SEL(Dtype, ASCENDC_TPL_UI_LIST, LPLOSS_TPL_FP32)),

    ASCENDC_TPL_ARGS_SEL(
        REDUCE_TPL_KEY_SEL_A(),
        ASCENDC_TPL_UINT_SEL(Reduction, ASCENDC_TPL_UI_LIST, LPLOSS_SUM, LPLOSS_MEAN),
        ASCENDC_TPL_UINT_SEL(Dtype, ASCENDC_TPL_UI_LIST, LPLOSS_TPL_FP32)));
#endif