/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */


/* !
 * \file gemm_v3_tiling_key.h
 * \brief
 */
#ifndef __OP_KERNEL_GEMM_V3_TILING_KEY_H__
#define __OP_KERNEL_GEMM_V3_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"

#define MAT_MUL_BASIC_LEVEL 1 // 数据类型定义
#define MAT_MUL_HIGH_LEVEL 0

#define MAT_MUL_NO_TRANS 0 //  数据格式定义
#define MAT_MUL_TRANS 1

#define MAT_MUL_FOR_BATCH 0
#define MAT_MUL_ITER_BATCH_SINGLE_BIAS 1
#define MAT_MUL_ITER_BATCH_BATCH_BIAS 2

#define MAT_MUL_BASIC 0
#define MAT_MUL_STREAM_K 1

#define MAT_MUL_NO_FULL_LOAD 0
#define MAT_MUL_A_FULL_LOAD 1
#define MAT_MUL_B_FULL_LOAD 2
#define MAT_MUL_AB_FULL_LOAD 3

#define MAT_MUL_ON_THE_FLY 0
#define MAT_MUL_1V1_ND_ALIG_FIXPIPE 1
#define MAT_MUL_1V2_ND_ALIG_FIXPIPE 2

// 模板参数
ASCENDC_TPL_ARGS_DECL(
    GemmV3, // 算子OpType
    ASCENDC_TPL_UINT_DECL(
        API_LEVEL, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, MAT_MUL_HIGH_LEVEL, MAT_MUL_BASIC_LEVEL),
    ASCENDC_TPL_UINT_DECL(A_TRANS, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, MAT_MUL_NO_TRANS, MAT_MUL_TRANS),
    ASCENDC_TPL_UINT_DECL(B_TRANS, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, MAT_MUL_NO_TRANS, MAT_MUL_TRANS),
    ASCENDC_TPL_UINT_DECL(
        BATCH_MODEL, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, MAT_MUL_FOR_BATCH, MAT_MUL_ITER_BATCH_SINGLE_BIAS,
        MAT_MUL_ITER_BATCH_BATCH_BIAS),
    ASCENDC_TPL_UINT_DECL(
        MODEL, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, MAT_MUL_BASIC, MAT_MUL_STREAM_K),
    ASCENDC_TPL_UINT_DECL(
        FULL_LOAD, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, MAT_MUL_NO_FULL_LOAD, MAT_MUL_A_FULL_LOAD,
        MAT_MUL_B_FULL_LOAD, MAT_MUL_AB_FULL_LOAD),
    ASCENDC_TPL_UINT_DECL(
        L0C2OUT_MODEL, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, MAT_MUL_ON_THE_FLY, MAT_MUL_1V1_ND_ALIG_FIXPIPE,
        MAT_MUL_1V2_ND_ALIG_FIXPIPE));

// 模板参数组合
// 用于调用GET_TPL_TILING_KEY获取TilingKey时，接口内部校验TilingKey是否合法
ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIC_ONLY),
        ASCENDC_TPL_UINT_SEL(API_LEVEL, ASCENDC_TPL_UI_LIST, MAT_MUL_HIGH_LEVEL),
        ASCENDC_TPL_UINT_SEL(A_TRANS, ASCENDC_TPL_UI_LIST, MAT_MUL_NO_TRANS, MAT_MUL_TRANS),
        ASCENDC_TPL_UINT_SEL(B_TRANS, ASCENDC_TPL_UI_LIST, MAT_MUL_NO_TRANS, MAT_MUL_TRANS),
        ASCENDC_TPL_UINT_SEL(BATCH_MODEL, ASCENDC_TPL_UI_LIST, MAT_MUL_FOR_BATCH),
        ASCENDC_TPL_UINT_SEL(MODEL, ASCENDC_TPL_UI_LIST, MAT_MUL_BASIC),
        ASCENDC_TPL_UINT_SEL(FULL_LOAD, ASCENDC_TPL_UI_LIST, MAT_MUL_NO_FULL_LOAD),
        ASCENDC_TPL_UINT_SEL(L0C2OUT_MODEL, ASCENDC_TPL_UI_LIST, MAT_MUL_ON_THE_FLY))
); // __OP_KERNEL_GEMM_V3_TILING_KEY_H__
#endif
