/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file fused_mat_mul_tilingkey.h
 * \brief
 */

#ifndef FUSED_MAT_MUL_TILINGKEY_H
#define FUSED_MAT_MUL_TILINGKEY_H

#include "ascendc/host_api/tiling/template_argument.h"
#include "fused_mat_mul_tiling_key_public.h"
#if defined(__CCE_AICORE__)
#include "kernel_operator.h"
#endif

#if defined(ORIG_DTYPE_X1) && ((defined(DT_BF16) && ORIG_DTYPE_X1 == DT_BF16)) || \
    ((defined(DT_FLOAT16) && ORIG_DTYPE_X1 == DT_FLOAT16))
#define A16
#endif

// 模板参数
ASCENDC_TPL_ARGS_DECL(FusedMatMul, // 算子OpType
                      ASCENDC_TPL_UINT_DECL(API_LEVEL, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, MAT_MUL_HIGH_LEVEL,
                                            MAT_MUL_BASIC_LEVEL),
                      ASCENDC_TPL_UINT_DECL(TRANS_MODEL, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, F_NO_TRANS, F_A_TRANS,
                                            F_B_TRANS, F_AB_TRANS),
                      ASCENDC_TPL_UINT_DECL(BATCH_ITER_MODEL, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, MAT_MUL_FOR_BATCH),
                      ASCENDC_TPL_UINT_DECL(MODEL, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, MAT_MUL_BASIC,
                                            MAT_MUL_STREAM_K),
                      ASCENDC_TPL_UINT_DECL(FULL_LOAD, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, MAT_MUL_NO_FULL_LOAD,
                                            MAT_MUL_A_FULL_LOAD, MAT_MUL_B_FULL_LOAD),
                      ASCENDC_TPL_UINT_DECL(L0C2OUT_MODEL, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, MAT_MUL_ON_THE_FLY,
                                            MAT_MUL_1V1_ND_ALIG_FIXPIPE, MAT_MUL_1V2_ND_ALIG_FIXPIPE),
                      ASCENDC_TPL_UINT_DECL(OPTYPE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, F_OPTYPE_NONE, F_OPTYPE_ADD,
                                            F_OPTYPE_MUL, F_OPTYPE_GELU_ERF, F_OPTYPE_GELU_TANH, F_OPTYPE_RELU));
ASCENDC_TPL_SEL(
#if !defined(__CCE_AICORE__) || defined(__DAV_C310__)
#if !defined(__CCE_AICORE__) || defined(A16)
    // [adv api]: gelu_erf, gelu_tanh
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(API_LEVEL, ASCENDC_TPL_UI_LIST, MAT_MUL_HIGH_LEVEL),
        ASCENDC_TPL_UINT_SEL(TRANS_MODEL, ASCENDC_TPL_UI_LIST, F_NO_TRANS, F_A_TRANS, F_B_TRANS, F_AB_TRANS),
        ASCENDC_TPL_UINT_SEL(BATCH_ITER_MODEL, ASCENDC_TPL_UI_LIST, MAT_MUL_FOR_BATCH),
        ASCENDC_TPL_UINT_SEL(MODEL, ASCENDC_TPL_UI_LIST, MAT_MUL_BASIC),
        ASCENDC_TPL_UINT_SEL(FULL_LOAD, ASCENDC_TPL_UI_LIST, MAT_MUL_NO_FULL_LOAD),
        ASCENDC_TPL_UINT_SEL(L0C2OUT_MODEL, ASCENDC_TPL_UI_LIST, MAT_MUL_ON_THE_FLY),
        ASCENDC_TPL_UINT_SEL(
            OPTYPE, ASCENDC_TPL_UI_LIST, F_OPTYPE_GELU_ERF, F_OPTYPE_GELU_TANH)),
#endif
    // streamK[basic api]: none, relu
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(API_LEVEL, ASCENDC_TPL_UI_LIST, MAT_MUL_BASIC_LEVEL),
        ASCENDC_TPL_UINT_SEL(TRANS_MODEL, ASCENDC_TPL_UI_LIST, F_NO_TRANS, F_A_TRANS, F_B_TRANS, F_AB_TRANS),
        ASCENDC_TPL_UINT_SEL(BATCH_ITER_MODEL, ASCENDC_TPL_UI_LIST, MAT_MUL_FOR_BATCH),
        ASCENDC_TPL_UINT_SEL(MODEL, ASCENDC_TPL_UI_LIST, MAT_MUL_STREAM_K),
        ASCENDC_TPL_UINT_SEL(FULL_LOAD, ASCENDC_TPL_UI_LIST, MAT_MUL_NO_FULL_LOAD),
        ASCENDC_TPL_UINT_SEL(L0C2OUT_MODEL, ASCENDC_TPL_UI_LIST, MAT_MUL_ON_THE_FLY, MAT_MUL_1V2_ND_ALIG_FIXPIPE),
        ASCENDC_TPL_UINT_SEL(OPTYPE, ASCENDC_TPL_UI_LIST, F_OPTYPE_NONE, F_OPTYPE_RELU)),
    // asw[basic api]: none, relu
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIC_ONLY),
        ASCENDC_TPL_UINT_SEL(API_LEVEL, ASCENDC_TPL_UI_LIST, MAT_MUL_BASIC_LEVEL),
        ASCENDC_TPL_UINT_SEL(TRANS_MODEL, ASCENDC_TPL_UI_LIST, F_NO_TRANS, F_A_TRANS, F_B_TRANS, F_AB_TRANS),
        ASCENDC_TPL_UINT_SEL(BATCH_ITER_MODEL, ASCENDC_TPL_UI_LIST, MAT_MUL_FOR_BATCH),
        ASCENDC_TPL_UINT_SEL(MODEL, ASCENDC_TPL_UI_LIST, MAT_MUL_BASIC),
        ASCENDC_TPL_UINT_SEL(
            FULL_LOAD, ASCENDC_TPL_UI_LIST, MAT_MUL_NO_FULL_LOAD),
        ASCENDC_TPL_UINT_SEL(L0C2OUT_MODEL, ASCENDC_TPL_UI_LIST, MAT_MUL_ON_THE_FLY),
        ASCENDC_TPL_UINT_SEL(OPTYPE, ASCENDC_TPL_UI_LIST, F_OPTYPE_NONE, F_OPTYPE_RELU)),
    // basic api with MAT_MUL_ON_THE_FLY: add, mul
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(API_LEVEL, ASCENDC_TPL_UI_LIST, MAT_MUL_BASIC_LEVEL),
        ASCENDC_TPL_UINT_SEL(TRANS_MODEL, ASCENDC_TPL_UI_LIST, F_NO_TRANS, F_A_TRANS, F_B_TRANS, F_AB_TRANS),
        ASCENDC_TPL_UINT_SEL(BATCH_ITER_MODEL, ASCENDC_TPL_UI_LIST, MAT_MUL_FOR_BATCH),
        ASCENDC_TPL_UINT_SEL(MODEL, ASCENDC_TPL_UI_LIST, MAT_MUL_BASIC),
        ASCENDC_TPL_UINT_SEL(
            FULL_LOAD, ASCENDC_TPL_UI_LIST, MAT_MUL_NO_FULL_LOAD),
        ASCENDC_TPL_UINT_SEL(L0C2OUT_MODEL, ASCENDC_TPL_UI_LIST, MAT_MUL_ON_THE_FLY),
        ASCENDC_TPL_UINT_SEL(OPTYPE, ASCENDC_TPL_UI_LIST, F_OPTYPE_ADD, F_OPTYPE_MUL)),
#endif
#if !defined(__CCE_AICORE__) || (defined(__NPU_ARCH__) && (__NPU_ARCH__ == 5102))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIC_ONLY),
        ASCENDC_TPL_UINT_SEL(API_LEVEL, ASCENDC_TPL_UI_LIST, MAT_MUL_HIGH_LEVEL),
        ASCENDC_TPL_UINT_SEL(TRANS_MODEL, ASCENDC_TPL_UI_LIST, F_NO_TRANS, F_A_TRANS, F_B_TRANS, F_AB_TRANS),
        ASCENDC_TPL_UINT_SEL(BATCH_ITER_MODEL, ASCENDC_TPL_UI_LIST, MAT_MUL_FOR_BATCH),
        ASCENDC_TPL_UINT_SEL(MODEL, ASCENDC_TPL_UI_LIST, MAT_MUL_BASIC),
        ASCENDC_TPL_UINT_SEL(FULL_LOAD, ASCENDC_TPL_UI_LIST, MAT_MUL_NO_FULL_LOAD),
        ASCENDC_TPL_UINT_SEL(L0C2OUT_MODEL, ASCENDC_TPL_UI_LIST, MAT_MUL_ON_THE_FLY),
        ASCENDC_TPL_UINT_SEL(OPTYPE, ASCENDC_TPL_UI_LIST, F_OPTYPE_RELU)),
#endif
);
#endif // FUSED_MAT_MUL_TILINGKEY_H