/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* !
 * \file weight_quant_batch_matmul_v2_tiling_key.h
 * \brief
 */

#ifndef WEIGHT_QUANT_BATCH_MATMUL_V2_ARCH35_TILING_KEY_H
#define WEIGHT_QUANT_BATCH_MATMUL_V2_ARCH35_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"
#include "weight_quant_batch_matmul_v2_arch35_tiling_data.h"

#if defined(ORIG_DTYPE_X) && ((defined(DT_BF16) && ORIG_DTYPE_X == DT_BF16)) || \
    ((defined(DT_FLOAT16) && ORIG_DTYPE_X == DT_FLOAT16))
#define A16
#endif
#if defined(ORIG_DTYPE_WEIGHT) && \
    ((defined(DT_INT4) && ORIG_DTYPE_WEIGHT == DT_INT4) || (defined(DT_INT32) && ORIG_DTYPE_WEIGHT == DT_INT32))
#define S4
#undef DTYPE_WEIGHT
#define DTYPE_WEIGHT AscendC::int4b_t
#undef ORIG_DTYPE_WEIGHT
#define ORIG_DTYPE_WEIGHT DT_INT4
#endif
#if defined(ORIG_DTYPE_ANTIQUANT_SCALE) && (ORIG_DTYPE_ANTIQUANT_SCALE == DT_FLOAT8_E8M0)
#define MICROSCALING
#endif
#if !defined(MICROSCALING) && defined(ORIG_DTYPE_WEIGHT) &&              \
    ((defined(DT_FLOAT4_E2M1) && ORIG_DTYPE_WEIGHT == DT_FLOAT4_E2M1) || \
     (defined(DT_FLOAT4_E1M2) && ORIG_DTYPE_WEIGHT == DT_FLOAT4_E1M2) || \
     (defined(DT_FLOAT) && ORIG_DTYPE_WEIGHT == DT_FLOAT))
#define F4
#if (defined(DT_FLOAT) && ORIG_DTYPE_WEIGHT == DT_FLOAT)
#undef DTYPE_WEIGHT
#define DTYPE_WEIGHT fp4x2_e2m1_t
#endif
#endif
#if defined(ORIG_DTYPE_WEIGHT) && (defined(DT_INT8) && ORIG_DTYPE_WEIGHT == DT_INT8)
#define S8
#endif
#if defined(ORIG_DTYPE_X) && defined(DT_BF16) && ORIG_DTYPE_X == DT_BF16
#define X_BF16
#endif
#if defined(FORMAT_WEIGHT) && defined(FORMAT_FRACTAL_NZ) && FORMAT_WEIGHT != FORMAT_FRACTAL_NZ
#define WEIGHT_ND
#endif

#if !defined(__DAV_310R6__)
#if defined(ORIG_DTYPE_WEIGHT)
#if (                                                                                                               \
    ORIG_DTYPE_WEIGHT == DT_INT8 || ORIG_DTYPE_WEIGHT == DT_FLOAT8_E5M2 || ORIG_DTYPE_WEIGHT == DT_FLOAT8_E4M3FN || \
    ORIG_DTYPE_WEIGHT == DT_HIFLOAT8)
#define WEIGHT_B8_BRANCH
#endif
#if (ORIG_DTYPE_WEIGHT == DT_FLOAT8_E5M2 || ORIG_DTYPE_WEIGHT == DT_FLOAT8_E4M3FN || ORIG_DTYPE_WEIGHT == DT_HIFLOAT8)
#define WEIGHT_F8_INPUT
#endif
#endif
#if defined(ORIG_DTYPE_WEIGHT) && defined(DT_FLOAT) && ORIG_DTYPE_WEIGHT == DT_FLOAT
#undef DTYPE_WEIGHT
#define DTYPE_WEIGHT fp4x2_e2m1_t
#endif
#endif

#define WQBMMV2_SOC_RESERVERD 0 // 平台大类
#define WQBMMV2_SOC_SUPPORT_L0C_TO_OUT 1
#define WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16 2
#define WQBMMV2_SOC_SUPPORT_MMAD_S8S4 3
#define WQBMMV2_SOC_PLACEHOLDER_4 4
#define WQBMMV2_SOC_ASCEND910_55 5

#define WQBMMV2_DEFAULT 0

#define WQBMMV2_ALGO_VECTOR_ANTIQUANT 0 // 算法大类
#define WQBMMV2_ALGO_MULTI_SCALE_DEQUANT 1
#define WQBMMV2_ALGO_FIXPIPE_ANTIQUANT 2
#define WQBMMV2_ALGO_CUSTOM 3

#define WQBMMV2_SUB_ALGO_VDEFAULT 0 // 算法小类-新
#define WQBMMV2_SUB_ALGO_SPLIT_K 1
#define WQBMMV2_SUB_ALGO_N_FIRST_TAIL_RESPLIT 2
#define WQBMMV2_SUB_ALGO_N_FIRST_BASIC_BLOCK 3
#define WQBMMV2_SUB_ALGO_ASW 4
#define WQBMMV2_SUB_ALGO_ANTI_REG_SCSC 5

#define WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_2 0
#define WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_4 1
#define WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_1024_BUF_NUM_2 2
#define WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_256_BUF_NUM_4 3
#define WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_DEFAULT 4
#define WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_256_BUF_NUM_2 5
#define WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_1024_BUF_NUM_4 6

#define WQBMMV2_ANTIQUANT_TYPE_NONE 0 // 反量化类型
#define WQBMMV2_ANTIQUANT_TYPE_PER_TENSOR 1
#define WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL 2
#define WQBMMV2_ANTIQUANT_TYPE_PER_GROUP 3
#define WQBMMV2_ANTIQUANT_TYPE_MX 4

#define WQBMMV2_QUANT_TYPE_NONE 0 // 量化类型
#define WQBMMV2_QUANT_TYPE_NOT_USE 1
#define WQBMMV2_QUANT_TYPE_PER_TENSOR 1
#define WQBMMV2_QUANT_TYPE_PER_CHANNEL 2
#define WQBMMV2_QUANT_TYPE_PER_GROUP 3
#define WQBMMV2_QUANT_TYPE_MX 4

ASCENDC_TPL_ARGS_DECL(
    WeightQuantBatchMatmulV2,
    ASCENDC_TPL_UINT_DECL( // 平台大类
        SOC_VERSION_TYPE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
        WQBMMV2_SOC_RESERVERD,
        WQBMMV2_SOC_SUPPORT_L0C_TO_OUT,
        WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16,
        WQBMMV2_SOC_SUPPORT_MMAD_S8S4,
        WQBMMV2_SOC_PLACEHOLDER_4,
        WQBMMV2_SOC_ASCEND910_55),
    ASCENDC_TPL_UINT_DECL( // 平台小类
        SUB_SOC_VERSION_TYPE, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST,
        WQBMMV2_DEFAULT),
    ASCENDC_TPL_UINT_DECL( // 伪量化场景
        ANTIQUANT_SCENARIO, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST,
        WQBMMV2_DEFAULT),
    ASCENDC_TPL_UINT_DECL( // 算法大类
        ALGORITHM, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
        WQBMMV2_ALGO_VECTOR_ANTIQUANT,
        WQBMMV2_ALGO_MULTI_SCALE_DEQUANT,
        WQBMMV2_ALGO_FIXPIPE_ANTIQUANT),
    ASCENDC_TPL_UINT_DECL( // 算法小类-19位tilingkey用
        SUB_ALGORITHM, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
        WQBMMV2_SUB_ALGO_VDEFAULT,
        WQBMMV2_SUB_ALGO_SPLIT_K,
        WQBMMV2_SUB_ALGO_N_FIRST_TAIL_RESPLIT,
        WQBMMV2_SUB_ALGO_N_FIRST_BASIC_BLOCK,
        WQBMMV2_SUB_ALGO_ASW,
        WQBMMV2_SUB_ALGO_ANTI_REG_SCSC,),
    ASCENDC_TPL_UINT_DECL( // 模板自定义
        TEMPLATE_CUSTOM, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
        WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_2,
        WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_4,
        WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_1024_BUF_NUM_2,
        WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_256_BUF_NUM_4,
        WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_DEFAULT,
        WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_256_BUF_NUM_2,
        WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_1024_BUF_NUM_4),
    ASCENDC_TPL_UINT_DECL( // api常量保留
        API_CONSTEXPR, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST,
        WQBMMV2_DEFAULT),
    ASCENDC_TPL_BOOL_DECL( // 转置场景
        TRANS_A, 0, 1),
    ASCENDC_TPL_BOOL_DECL( // 转置场景
        TRANS_B, 0, 1),
    ASCENDC_TPL_UINT_DECL( // 反量化类型
        ANTIQUANT_TYPE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
        WQBMMV2_ANTIQUANT_TYPE_NONE,
        WQBMMV2_ANTIQUANT_TYPE_PER_TENSOR,
        WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL,
        WQBMMV2_ANTIQUANT_TYPE_PER_GROUP,
        WQBMMV2_ANTIQUANT_TYPE_MX),
    ASCENDC_TPL_UINT_DECL( // 量化类型
        QUANT_TYPE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
        WQBMMV2_QUANT_TYPE_NONE,
        WQBMMV2_QUANT_TYPE_PER_TENSOR,
        WQBMMV2_QUANT_TYPE_PER_CHANNEL,
        WQBMMV2_QUANT_TYPE_PER_GROUP,
        WQBMMV2_QUANT_TYPE_MX),
    ASCENDC_TPL_BOOL_DECL( // 可选输入
        HAS_ANTIQUANT_OFFSET, 0, 1),
    ASCENDC_TPL_BOOL_DECL( // 可选输入
        HAS_BIAS, 0, 1),
    ASCENDC_TPL_BOOL_DECL( // 可选输入
        IS_BIAS_FP32, 0, 1),
    ASCENDC_TPL_BOOL_DECL( // weight的格式
        IS_WEIGHT_NZ, 0, 1),
);
ASCENDC_TPL_SEL(
#if !defined(__CCE_AICORE__) || (!defined(__DAV_310R6__) && !(defined(__NPU_ARCH__) && (__NPU_ARCH__ == 5102)))
    #if !defined(__CCE_AICORE__) || (defined(MICROSCALING) && !defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_TAIL_RESPLIT),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_4, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_256_BUF_NUM_4),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_MX),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 0),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 1),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
    #endif
    #if !defined(__CCE_AICORE__) || (defined(MICROSCALING) && defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_TAIL_RESPLIT),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_1024_BUF_NUM_2),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 1),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_MX),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 0),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_BASIC_BLOCK),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_256_BUF_NUM_4),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_MX),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 0),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
    #endif
    #if !defined(__CCE_AICORE__) || ((defined(S8) || defined(S4)) && defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_ANTI_REG_SCSC),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_2),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0, 1),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_GROUP),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_NONE),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 0),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
    #endif
    #if !defined(__CCE_AICORE__) || ((defined(S4) || defined(F4)) && !defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_ANTI_REG_SCSC),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_2),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_GROUP),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_NONE),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 0),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 1),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2RegBaseTilingDataParams)
    ),
    #endif
    #if !defined(__CCE_AICORE__) || (defined(S4) && !defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_TAIL_RESPLIT),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_256_BUF_NUM_4),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 0),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 1),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
    #endif
    #if !defined(__CCE_AICORE__) || (defined(S4) && !defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_TAIL_RESPLIT),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_4, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_1024_BUF_NUM_2, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_1024_BUF_NUM_4),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_GROUP),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 0),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 1),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
    #endif
    #if !defined(__CCE_AICORE__) || ((defined(S8) || defined(S4)) && defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_BASIC_BLOCK),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_DEFAULT),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 1),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_NOT_USE),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 0),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
    #endif
    #if !defined(__CCE_AICORE__) || ((defined(S8) || defined(WEIGHT_F8_INPUT) || defined(S4)) && defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_BASIC_BLOCK),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_256_BUF_NUM_4),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_NOT_USE),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 0),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
    #endif
    #if !defined(__CCE_AICORE__) || ((defined(S8) || defined(S4)) && defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_BASIC_BLOCK),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_256_BUF_NUM_4),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_NOT_USE),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 0),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
    #endif
    #if !defined(__CCE_AICORE__) || ((defined(S8) || defined(WEIGHT_F8_INPUT) || defined(S4)) && defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_TAIL_RESPLIT),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_2, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_4, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_1024_BUF_NUM_2, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_256_BUF_NUM_4),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 1),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 0),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
    #endif
    #if !defined(__CCE_AICORE__) || (defined(ORIG_DTYPE_X) && defined(DT_BF16) && ORIG_DTYPE_X == DT_BF16)
        #if !defined(__CCE_AICORE__) || (defined(MICROSCALING) && !defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_TAIL_RESPLIT),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_4, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_256_BUF_NUM_4),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_MX),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 1),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 1),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
        #endif
        #if !defined(__CCE_AICORE__) || (defined(MICROSCALING) && defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_TAIL_RESPLIT),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_1024_BUF_NUM_2),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 1),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_MX),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 1),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_BASIC_BLOCK),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_256_BUF_NUM_4),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_MX),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 1),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
        #endif
        #if !defined(__CCE_AICORE__) || ((defined(S8) || defined(S4)) && defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_ANTI_REG_SCSC),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_2),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0, 1),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_GROUP),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_NONE),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 1),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
        #endif
        #if !defined(__CCE_AICORE__) || ((defined(S4) || defined(F4)) && !defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_ANTI_REG_SCSC),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_2),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_GROUP),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_NONE),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 1),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 1),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2RegBaseTilingDataParams)
    ),
        #endif
        #if !defined(__CCE_AICORE__) || (defined(S4) && !defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_TAIL_RESPLIT),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_256_BUF_NUM_4),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 1),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 1),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
        #endif
        #if !defined(__CCE_AICORE__) || (defined(S4) && !defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_TAIL_RESPLIT),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_4, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_1024_BUF_NUM_2, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_1024_BUF_NUM_4),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_GROUP),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 1),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 1),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
        #endif
        #if !defined(__CCE_AICORE__) || ((defined(S8) || defined(S4)) && defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_BASIC_BLOCK),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_DEFAULT),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 1),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_NOT_USE),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 1),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
        #endif
        #if !defined(__CCE_AICORE__) || ((defined(S8) || defined(WEIGHT_F8_INPUT) || defined(S4)) && defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_BASIC_BLOCK),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_256_BUF_NUM_4),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_NOT_USE),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 1),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
        #endif

        #if !defined(__CCE_AICORE__) || ((defined(S8) || defined(S4)) && defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_BASIC_BLOCK),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_256_BUF_NUM_4),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_NOT_USE),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 1),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
        #endif
        #if !defined(__CCE_AICORE__) || ((defined(S8) || defined(WEIGHT_F8_INPUT) || defined(S4)) && defined(WEIGHT_ND))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_L1_TO_BT_BF16),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_TAIL_RESPLIT),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_2, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_4, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_1024_BUF_NUM_2, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_256_BUF_NUM_4),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 1),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 1),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
        #endif
    #endif
#endif
#if !defined(__CCE_AICORE__) || (defined(__DAV_310R6__))
    #if !defined(__CCE_AICORE__) || (defined(FORMAT_WEIGHT) && (FORMAT_WEIGHT != FORMAT_FRACTAL_NZ))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_1),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_ASCEND910_55),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_BASIC_BLOCK),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_2),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 1),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 0),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_1),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_ASCEND910_55),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_BASIC_BLOCK),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_256_BUF_NUM_2),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 0),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
    #endif
    #if !defined(__CCE_AICORE__) || (defined(ORIG_DTYPE_X) && defined(DT_BF16) && ORIG_DTYPE_X == DT_BF16)
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_1),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_ASCEND910_55),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_BASIC_BLOCK),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_2),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 1),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 1),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_1),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_ASCEND910_55),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_VECTOR_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_N_FIRST_BASIC_BLOCK),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_256_BUF_NUM_2),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 1),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASTilingDataParams)
    ),
    #endif
#endif
#if !defined(__CCE_AICORE__) || (defined(__NPU_ARCH__) && (__NPU_ARCH__ == 5102))
    #if !defined(__CCE_AICORE__) || (defined(FORMAT_WEIGHT) && (FORMAT_WEIGHT != FORMAT_FRACTAL_NZ))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIC_ONLY),
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_SOC_SUPPORT_MMAD_S8S4),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_SCENARIO, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_ALGO_FIXPIPE_ANTIQUANT),
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_ASW),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_TEMPLATE_MTE2_INNER_SIZE_512_BUF_NUM_2),
        ASCENDC_TPL_UINT_SEL(API_CONSTEXPR, ASCENDC_TPL_UI_LIST, WQBMMV2_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0, 1),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0, 1),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_TENSOR, WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL),
        ASCENDC_TPL_UINT_SEL(QUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_QUANT_TYPE_PER_TENSOR, WQBMMV2_QUANT_TYPE_NONE),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0),
        ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0, 1),
        ASCENDC_TPL_BOOL_SEL(IS_BIAS_FP32, 0),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 0),
        ASCENDC_TPL_TILING_STRUCT_SEL(wqbmmv2_tiling::WeightQuantBatchMatmulV2ASWTilingDataParams)
    ),
    #endif
#endif
);

#endif // WEIGHT_QUANT_BATCH_MATMUL_V2_ARCH35_TILING_KEY_H
